on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cake-build/cake-action@v1
        with:
          cake-version: 0.34.1
      - uses: actions/upload-artifact@v1
        with:
          name: packs
          path: *.mcpack
